### ISSUE TITLE
Chained requests queued

### ISSUE THREAD

**Issue by kalkih** [phillipsnick/denon-avr#11]
Hey Nick,

I'm trying to do some chained requests with your node package for my Denon AVR but I can't get it to work.
Below is some example code where I'm using the setVolumeUp() two times with a 2000ms timeout between the first and the second volume up.
```js
var denon = require('denon-avr');
var config = require('./config');
var avr = new denon(new denon.transports.telnet(config));
avr.connect();

avr.on('connect', function() {
  console.log('Connected to AVR');
  
  avr.setVolumeUp(function(err, volume) {
    if (err) {
      console.log(err.toString());
      return;
    }
    console.log('The volume is', volume, '/', avr.parseAsciiVolume(volume), 'dB');
  });
  
  setTimeout(function() {
    avr.setVolumeUp(function(err, volume) {
    if (err) {
      console.log(err.toString());
      return;
    }
    console.log('The volume is', volume, '/', avr.parseAsciiVolume(volume), 'dB');
  });
  }, 2000);
  
});
```

And as you can see from the debug log The first volume up command works fine but then the second one just gets queued. I also get a Connection timeout in the log on the second last row, I'm not sure if that should be there?

```
5/5/2015 20:22:20 Successfully connected
5/5/2015 20:22:20 Setting telnet state to: connected
5/5/2015 20:22:20 Setting telnet state to: ready
Connected to AVR
5/5/2015 20:22:20 Queuing: MVUP
5/5/2015 20:22:20 Writing: MVUP
5/5/2015 20:22:20 Setting telnet state to: response
5/5/2015 20:22:20 Creating response timeout of 200ms
5/5/2015 20:22:20 Received:
5/5/2015 20:22:20 MV235
5/5/2015 20:22:20 <Buffer 4d 56 32 33 35 0d>
5/5/2015 20:22:20 Received:
5/5/2015 20:22:20 MVMAX 80
5/5/2015 20:22:20 <Buffer 4d 56 4d 41 58 20 38 30 0d>
5/5/2015 20:22:21 Response ready with:
5/5/2015 20:22:21 [ 'MV235', 'MVMAX 80' ]
The volume is 235 / -56.5 dB
5/5/2015 20:22:21 Setting telnet state to: ready
5/5/2015 20:22:21 Connection timeout
5/5/2015 20:22:22 Queuing: MVUP
```

Is this a issue or am I doing something wrong?

Thanks!
Regards,
Kalle Kihlström

**Comment by phillipsnick** [comment]
Hi

Code looks fine but it seems the telnet connection is timing out before it gets chance to send the next command.

Specifically these lines from the log:

```
5/5/2015 20:22:21 Setting telnet state to: ready
5/5/2015 20:22:21 Connection timeout
5/5/2015 20:22:22 Queuing: MVUP
```

I'll give the above code a go on my amp tomorrow and see what I can come up with.

Nick

**Comment by kalkih** [comment]
Hey,

Yeah, the connection seems to timeout after about half a second or less after the first command is done.

Looking forward to your results.

Thanks.
//Kalle

**Comment by kalkih** [comment]
Did you have time to try the code?

Regards,
Kalle

**Comment by syedmehdi** [comment]
It looks like there are 2 timeouts used in telnet-client.js.  Setting these in your config.js file will resolve the timeout your seeing.

sample config.js: 
`module.exports = {
  host: '192.168.0.101',
  debug: true,
  timeout: 5000,
  execTimeout: 5000,
}`

**Comment by phillipsnick** [comment]
Thanks to a fix by arseneyr here in the telnet client https://github.com/phillipsnick/node-telnet-client/commit/086a30f835ea1b9959a69efc30e9f475ac9503dd

Chained requests should now work properly. I have created this example: https://github.com/phillipsnick/denon-avr/blob/master/examples/telnet/chain.js which works fine on my amp.

Let me know if this resolves your issue.

**Comment by aborovsky** [comment]
One may close this bug!
I've tested script 

```
var denon = require('denon-avr');
var config = require('./config');
var avr = new denon(new denon.transports.telnet(config));
avr.connect();

avr.on('connect', function() {
  console.log('Connected to AVR');

  avr.setVolumeUp(function(err, volume) {
    if (err) {
      console.log(err.toString());
      return;
    }
    console.log('The volume is', volume, '/', avr.parseAsciiVolume(volume), 'dB');
  });

  setTimeout(function() {
    avr.setVolumeUp(function(err, volume) {
    if (err) {
      console.log(err.toString());
      return;
    }
    console.log('The volume is', volume, '/', avr.parseAsciiVolume(volume), 'dB');
  });
  }, 2000);

});
```

with latest master branch and Denon AVR-X1200W.
It's working lika a charm. Both two commands handled successfully!

**Comment by phillipsnick** [comment]
Thanks
